import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import '@/styles/globals.css'
import { Hind } from 'next/font/google'

const hind = Hind({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={hind.className}>
      <body>
        <Header />
        <main style={{ minHeight: 'calc(100vh - 96px)' }}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
